project:
  type: book
  output-dir: docs
 
lang: fr 
  
book:
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    left: "Marc Thévenin / Ined-Sms / Juin 2023" 
    background: dark
  navbar:
    left: 
      - href: https://mthevenin.github.io/stata_fr/index.html
        text: "Stata Ined"
      - href: https://mthevenin.github.io/stata_fr/articles/
        text: "Articles"
      - text: Formations
        menu: 
          - text: "Formation initiale"
            href: https://mthevenin.github.io/stata_programmation/
          - text: "Graphiques"
            href: https://mthevenin.github.io/stata_graphiques/   
  title: "Programmation avec Stata"
  author: "**Marc Thévenin**"
  language: fr
  output-file: stata_programmation
  downloads: [pdf]
  repo-url: https://github.com/mthevenin/stata_programmation
  repo-actions: [edit]
  date: today
  reader-mode: false
  sidebar:
    style: "docked"
    collapse-level: 1
    tools: 
      - icon: github
        href: https://github.com/mthevenin
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
  chapters:
    - index.qmd  
    - chapitre1.qmd
    - chapitre2.qmd 
    - chapitre3.qmd
    - chapitre4.qmd
    - chapitre5.qmd
    - chapitre6.qmd
    - chapitre7.qmd

format:
  html:
    theme: 
      light:  [yeti, theme-light.scss]          
    css: styles.css
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    highlight-style: dracula
    number-sections: true
    grid:
      sidebar-width: 350px
      body-width: 950px
      margin-width: 300px
      gutter-width: 1.5rem

  pdf:
    fontsize: 12pt
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    number-sections: true
    toc: true
#    lot: true
#    lof: true
    cap-location: top
    colorlinks: true
    highlight-style: zenburn
    fontfamily: cabin 
    toc-depth: 4
    geometry: 
      - top=20mm
      - left=15mm
      - right=15mm
      - bottom=20mm  

filters:
   - lightbox
lightbox: auto







