project:
  type: website
  output-dir: docs
  
website:
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    left: "Marc Thévenin / Ined-Sms / Mai 2023" 
    background: dark
  navbar:
    collapse-below: lg
    left:
      - href: https://mthevenin.github.io/stata_fr/
        text: "Stata Ined"  
      - href: https://mthevenin.github.io/stata_graphiques/
        text: "Graphiques"
      - href: https://mthevenin.github.io/stata_programmation/
        text: "Programmation"

  sidebar:
    pinned: true
    align: center
    tools: 
      - href: about.qmd
      - icon: github
        href: https://github.com/mthevenin
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
      - icon: file-person
        href: about.qmd  
  
    style: "docked"
    collapse-level: 1    
    contents:
      - section: "Formation introductive"
        contents:
          - formation/chapitre0.qmd
          - formation/chapitre1.qmd
          - formation/chapitre2.qmd 
          - formation/chapitre3.qmd
          - formation/chapitre4.qmd
          - formation/chapitre5.qmd
          - formation/chapitre6.qmd
          - formation/chapitre7.qmd
          - text: "  "  
      - section: "Fichier profile"
        contents:
          - profile/profile1.qmd  
          - profile/profile2.qmd
      - section: "Need for speed"
        contents:
          - speedup/gtools/gtools.qmd  
          - speedup/frame/frame.qmd           
      - section: "Super Macro World"
        contents:
          - macro/intro.qmd        
      - section: "C'est dans l'R"
        contents:
          - R.qmd   
      - section: "Edition des outputs"
        contents:
          - tableaux/intro.qmd        

format:
  html:
    theme: 
      light:  [yeti, theme-light.scss]          
    css: styles.css
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    highlight-style: dracula
number-sections: true
filters:
   - lightbox
lightbox: auto

