---
title: "Présentation"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



* N'intéressera peut-être pas les utilisatrices et utilisateurs aguerri.e.s à Stata.... quoique. On trouve toujours des années plus tard des nouvelles commandes qui facilitent vraiment les choses,  ou une introduction aux frames, qui revisitent les appariements de bases.
* Les chapitres sont téléchargeables en format docx. 


* Maj dela formation:
  * 28/07/22 : **Les variables**. Chapitre 5 [todo: faire un topo sur les formats date avant fin 2023] 
  * 07/10/22 : **Introduction**.  Chapitre 1
  * 07/10/22 : **L'environnement**.  Chapitre 2
  * 22/02/23 : **Le langage Stata**. Chapitre 3
  * 22/02/23 : **Les bases de données**. Chapitre 4 [introduction aux *frame* introduites avec la v16]
  * 05/07/23 : **Opérations sur les bases de données**. Chapitre 6 [début reprise du chapitre] 

* Programmes des chapitres:
  *  [Chapitre3](formation/programme3.do)
  *  [Chapitre4](formation/programme4.do)
  *  [Chapitre5](formation/programme5.do)
  *  [Chapitre6](formation/programme6.do)



