---
title: ""
#css: styles.css
---

* Cette formation n'intéressera vraisemblablement pas les utilisatrices et utilisateurs aguerri.e.s à Stata.... quoique, on trouve toujours des années plus tard des nouvelles commandes qui facilitent vraiment les choses, par exemple sur la rapide reprise du chapitre 5, la commande `sencode` (s pour super). Mais également une introduction aux **frames**, qui revisitent les appariements de bases, et permettent de travailler sur plusieurs bases en parallèle.
* Les chapitres sont téléchargeables en format docx. 


* Maj de la formation de 2018:
  * 28/07/22 : **Les variables**. Chapitre 5 [todo: un topo sur les formats date] 
  * 07/10/22 : **Introduction**.  Chapitre 1
  * 07/10/22 : **L'environnement**.  Chapitre 2
  * 22/02/23 : **Le langage Stata**. Chapitre 3
  * 22/02/23 : **Les bases de données**. Chapitre 4 [introduction aux *frame* introduites avec la v16]

* Programmes des chapitres:
  *  [Chapitre3](formation/programme3.do)
  *  [Chapitre4](formation/programme4.do)
  *  [Chapitre5](formation/programme5.do)



---

-    Support réalisé avec [Posit-Rstudio](https://posit.co/) - [Quarto](https://quarto.org).
-    Version Stata: [17-SE](https://www.stata.com/)

